# Clippy configuration for flamewasm
warn-return-type = true

[lints.clippy]
all = "warn"
pedantic = "warn"
# Allow some pedantic lints that are too noisy
module-name-repetitions = "allow"
must-use-candidate = "allow"
missing-errors-doc = "allow"
missing-panics-doc = "allow"
# Safety
unwrap-used = "warn"
expect-used = "warn"
panic = "warn"
